[package]
name = "conhash"
version = "0.1.0"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]
descriptions = "Consistent Hashing library in Rust"
repository = "https://github.com/zonyitoo/conhash-rs"
keyword = ["consistent hashing", "hash"]
license = "MIT"

[lib]
name = "conhash"

[dependencies]
rust-crypto = "*"
log = "*"
env_logger = "*"
